repos:
    - repo: https://github.com/psf/black-pre-commit-mirror
      rev: 25.1.0
      hooks:
        - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.0.0
      hooks:
        - id: flake8
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.19.1
      hooks:
        - id: pyupgrade