site_name: Wafermap
# site_url: http://www.jieyu.ai
repo_url: https://github.com/cap1tan/wafermap
repo_name: wafermap
#strict: true
nav:
  - Home: index.md
  - Usage: usage.md
  - contributing: contributing.md
  - Authors: authors.md
  - History: history.md
theme:
  name: readthedocs
  language: en
  #logo: assets/logo.png
  palette:
    primary: light blue
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - wafermap
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cap1tan/wafermap
      name: Github
    - icon: material/email
      link: "mailto:sothomas88@gmail.com"
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
