[project]
name = "wafermap"
version = "0.3.2"
description = "A python package to plot maps of semiconductor wafers."
authors = [
    {name = "Sotiris Thomas", email = "sothomas88@gmail.com"}
]
readme = "README.md"
license = {text = "MIT"}
keywords = ["semiconductor", "wafer", "layout", "plot", "grid"]
requires-python = ">=3.10,<4.0"
dependencies = [
	"folium>=0.19.5",
	"branca>=0.6.0",
	"Pillow>=12.0.0",
	"numpy>=2.00.0",
	"html2image>=2.0.3"
]

[project.optional-dependencies]
test = [
	"black",
	"isort",
	"flake8",
	"flake8-docstrings",
	"pytest",
	"pytest-cov",
	# pre-commit = "^3.2.2"
	# toml = "^0.10.2"
	"pylint",
	"tox",
	"tox-poetry-installer",
	"twine"
]

# [tool.poetry.dependencies]
# python = ">=3.10"
# folium = { version = ">=0.19.5" }
# branca = { version = ">=0.6.0" }
# Pillow = { version = ">=11.1.0" }
# numpy = { version = ">=2.00.0"}
# html2image = { version = ">=2.0.3" }
# black = { optional = true }
# isort = { optional = true }
# flake8 = { optional = true }
# flake8-docstrings = { optional = true }
# pytest = { optional = true }
# pytest-cov = { optional = true }
# pylint = { optional = true }
# tox = { optional = true }
# twine = { optional = true }


[dependency-groups]
test=[
	"black",
	"isort",
	"flake8",
	"flake8-docstrings",
	"pytest",
	"pytest-cov",
	# pre-commit = "^3.2.2"
	# toml = "^0.10.2"
	"pylint",
	"tox",
	"tox-poetry-installer",
	"twine"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
