[tox]
requires =
    tox>=4
env_list = lint, 3.1{0,1,2,3,4}
isolated_build = true

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314	

[testenv]
description = Running tests and checking coverage
require_locked_deps = true
allowlist_externals = pytest, isort, black, flake8, pylint, poetry, twine
commands =
    pytest tests/ -s -v --cov=wafermap --cov-append --cov-report=xml --cov-report=term-missing --import-mode importlib --cov-fail-under=80

[testenv:lint]
description = Linting, checking style and reformatting
ignore_errors = false
commands =
    isort wafermap
    black wafermap tests
	flake8 wafermap tests
	pylint wafermap tests --fail-under=9
	poetry build
    twine check dist/*
